name: 'bumpr - Bump version when merging Pull Request with specific labels'
description: 'Bump version when merging Pull Request with specific labels (bump:major,bump:minor,bump:patch)'
author: 'haya14busa'
inputs:
  default_bump_level:
    description: "Default bump level if labels are not attached [major,minor,patch]. Do nothing if it's empty"
    required: false
  dry_run:
    description: "Do not actually tag next version if it's true"
    required: false
  github_token:
    description: 'GITHUB_TOKEN to list pull requests and create tags'
    default: '${{ github.token }}'
    required: true
  major_labels:
    description: 'Comma separated list of labels for major releases'
    default: 'bump:major'
  minor_labels:
    description: 'Comma separated list of labels for minor releases'
    default: 'bump:minor'
  patch_labels:
    description: 'Comma separated list of labels for patch releases'
    default: 'bump:patch'
  tag_as_user:
    description: "Name to use when creating tags"
    required: false
  tag_as_email:
    description: "Email address to use when creating tags"
    required: false
outputs:
  current_version:
    description: "current version"
    value: "${{ steps.bumpr.outputs.current_version }}"
  next_version:
    description: "next version"
    value: "${{ steps.bumpr.outputs.next_version }}"
  skip:
    description: "True if release is skipped. e.g. No labels attached to PR."
    value: "${{ steps.bumpr.outputs.skip }}"
  message:
    description: "Tag message"
    value: "${{ steps.bumpr.outputs.message }}"
runs:
  using: 'composite'
  steps:
    - id: bumpr
      run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        INPUT_DEFAULT_BUMP_LEVEL: ${{ inputs.default_bump_level }}
        INPUT_DRY_RUN: ${{ inputs.dry_run }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_MAJOR_LABELS: ${{ inputs.major_labels }}
        INPUT_MINOR_LABELS: ${{ inputs.minor_labels }}
        INPUT_PATCH_LABELS: ${{ inputs.patch_labels }}
        INPUT_TAG_AS_USER: ${{ inputs.tag_as_user }}
        INPUT_TAG_AS_EMAIL: ${{ inputs.tag_as_email }}


# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'corner-right-up'
  color: 'gray-dark'
